<a href="https://colab.research.google.com/github/SriSharanya-617/deeplearning/blob/main/CarPrice_Prediction_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
import pandas as pd
drive.mount('/content/drive')
path='/content/drive/MyDrive/Colab Notebooks/CarPrice_dataset.csv'
df=pd.read_csv(path)
df.head()

Mounted at /content/drive

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0

In [2]:
df.isnull().sum()

car_ID              0
symboling           0
CarName             0
fueltype            0
aspiration          0
doornumber          0
carbody             0
drivewheel          0
enginelocation      0
wheelbase           0
carlength           0
carwidth            0
carheight           0
curbweight          0
enginetype          0
cylindernumber      0
enginesize          0
fuelsystem          0
boreratio           0
stroke              0
compressionratio    0
horsepower          0
peakrpm             0
citympg             0
highwaympg          0
price               0
dtype: int64

In [4]:
from pandas.core.arrays import categorical
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer

X=df.drop(columns='price')
y=df['price']

# Identify categorical and numerical columns
categorical_cols = X.select_dtypes(include=['object']).columns.tolist()
numerical_cols = X.select_dtypes(include=['int64', 'float64']).columns.tolist ()

#Define Preprocessing steps
preprocessor = ColumnTransformer(
  transformers=[
    ('num', StandardScaler(), numerical_cols),
    ('car', OneHotEncoder(handle_unknown='ignore'), categorical_cols)
  ]
)

#Apply Preprocessing
X_processed=preprocessor.fit_transform(X)

#Split the data
X_train, X_test, y_train, y_test = train_test_split(X_processed, y, test_size=0.2, random_state=42)

In [6]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

#Define the model
model=Sequential([
  Dense(512, activation='relu', input_shape=(X_train.shape[1], )),
  Dense(256, activation='relu'),
  Dense(128, activation='relu'),
  Dense(64, activation='relu'),
  Dense(32, activation='relu'),
  Dense(1) # Output layer for regression
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [7]:
model.compile(optimizer='adam', loss='mean_absolute_error',
  metrics=['mean_absolute_error','mean_squared_error'])

In [9]:
history=model.fit(X_train,y_train,epochs=70,validation_split=0.2,verbose=1)

Epoch 1/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 5s 496ms/step - loss: 13041.3613 - mean_absolute_error: 13041.3613 - mean_squared_error: 219984528.0000 - val_loss: 15080.4219 - val_mean_absolute_error: 15080.4219 - val_mean_squared_error: 317856544.0000
Epoch 2/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 12758.0029 - mean_absolute_error: 12758.0029 - mean_squared_error: 218640704.0000 - val_loss: 15073.1289 - val_mean_absolute_error: 15073.1289 - val_mean_squared_error: 317621504.0000
Epoch 3/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 12874.8965 - mean_absolute_error: 12874.8965 - mean_squared_error: 219901392.0000 - val_loss: 15052.5869 - val_mean_absolute_error: 15052.5869 - val_mean_squared_error: 316969856.0000
Epoch 4/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 12555.1162 - mean_absolute_error: 12555.1162 - mean_squared_error: 209583248.0000 - val_loss: 15000.5205 - val_mean_absolute_error: 15000.5205 - val_mean_squared_error: 315352608.0000
Epoch 5/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 12889.7363 - mean_absolute_error: 12889.7363 - mean_squared_error: 222281840.0000 - val_loss: 14880.2480 - val_mean_absolute_error: 14880.2480 - val_mean_squared_error: 311747680.0000
Epoch 6/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 12490.1367 - mean_absolute_error: 12490.1367 - mean_squared_error: 211806464.0000 - val_loss: 14615.7539 - val_mean_absolute_error: 14615.7539 - val_mean_squared_error: 304021728.0000
Epoch 7/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 11847.4287 - mean_absolute_error: 11847.4287 - mean_squared_error: 189742576.0000 - val_loss: 14071.5322 - val_mean_absolute_error: 14071.5322 - val_mean_squared_error: 288962912.0000
Epoch 8/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 11560.2695 - mean_absolute_error: 11560.2695 - mean_squared_error: 185901472.0000 - val_loss: 13014.9775 - val_mean_absolute_error: 13014.9775 - val_mean_squared_error: 261961824.0000
Epoch 9/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 10678.6465 - mean_absolute_error: 10678.6465 - mean_squared_error: 170464720.0000 - val_loss: 11016.8662 - val_mean_absolute_error: 11016.8662 - val_mean_squared_error: 216794240.0000
Epoch 10/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 7577.0005 - mean_absolute_error: 7577.0005 - mean_squared_error: 112396144.0000 - val_loss: 8661.2539 - val_mean_absolute_error: 8661.2539 - val_mean_squared_error: 155281872.0000
Epoch 11/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 5988.5581 - mean_absolute_error: 5988.5581 - mean_squared_error: 79614992.0000 - val_loss: 7165.2046 - val_mean_absolute_error: 7165.2046 - val_mean_squared_error: 98396768.0000
Epoch 12/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 5304.1138 - mean_absolute_error: 5304.1138 - mean_squared_error: 45180476.0000 - val_loss: 5823.6118 - val_mean_absolute_error: 5823.6118 - val_mean_squared_error: 64471744.0000
Epoch 13/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 4864.2563 - mean_absolute_error: 4864.2563 - mean_squared_error: 43906288.0000 - val_loss: 4576.4131 - val_mean_absolute_error: 4576.4131 - val_mean_squared_error: 53979428.0000
Epoch 14/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 3079.9048 - mean_absolute_error: 3079.9048 - mean_squared_error: 24354212.0000 - val_loss: 4287.6929 - val_mean_absolute_error: 4287.6929 - val_mean_squared_error: 52552832.0000
Epoch 15/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 2931.2112 - mean_absolute_error: 2931.2112 - mean_squared_error: 28844922.0000 - val_loss: 3171.4954 - val_mean_absolute_error: 3171.4954 - val_mean_squared_error: 29464968.0000
Epoch 16/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 2250.7327 - mean_absolute_error: 2250.7327 - mean_squared_error: 17146440.0000 - val_loss: 2580.3408 - val_mean_absolute_error: 2580.3408 - val_mean_squared_error: 15863312.0000
Epoch 17/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 2502.6489 - mean_absolute_error: 2502.6489 - mean_squared_error: 14454841.0000 - val_loss: 2500.6089 - val_mean_absolute_error: 2500.6089 - val_mean_squared_error: 13796398.0000
Epoch 18/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - loss: 2101.0701 - mean_absolute_error: 2101.0701 - mean_squared_error: 10951604.0000 - val_loss: 2657.3037 - val_mean_absolute_error: 2657.3037 - val_mean_squared_error: 15407472.0000
Epoch 19/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 1973.9424 - mean_absolute_error: 1973.9424 - mean_squared_error: 10118092.0000 - val_loss: 2871.2666 - val_mean_absolute_error: 2871.2666 - val_mean_squared_error: 18239556.0000
Epoch 20/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - loss: 2018.4185 - mean_absolute_error: 2018.4185 - mean_squared_error: 11284433.0000 - val_loss: 2509.9167 - val_mean_absolute_error: 2509.9167 - val_mean_squared_error: 15243964.0000
Epoch 21/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 2036.3496 - mean_absolute_error: 2036.3496 - mean_squared_error: 11733564.0000 - val_loss: 2491.3442 - val_mean_absolute_error: 2491.3442 - val_mean_squared_error: 14570085.0000
Epoch 22/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - loss: 2003.3232 - mean_absolute_error: 2003.3232 - mean_squared_error: 9458279.0000 - val_loss: 2558.2415 - val_mean_absolute_error: 2558.2415 - val_mean_squared_error: 15696654.0000
Epoch 23/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 1770.9343 - mean_absolute_error: 1770.9343 - mean_squared_error: 9869485.0000 - val_loss: 2873.4983 - val_mean_absolute_error: 2873.4983 - val_mean_squared_error: 19255244.0000
Epoch 24/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 1831.9985 - mean_absolute_error: 1831.9985 - mean_squared_error: 10575853.0000 - val_loss: 2692.5530 - val_mean_absolute_error: 2692.5530 - val_mean_squared_error: 17390358.0000
Epoch 25/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 1606.0565 - mean_absolute_error: 1606.0565 - mean_squared_error: 9169762.0000 - val_loss: 2428.2310 - val_mean_absolute_error: 2428.2310 - val_mean_squared_error: 13062066.0000
Epoch 26/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 1754.6008 - mean_absolute_error: 1754.6008 - mean_squared_error: 6651478.0000 - val_loss: 2330.4683 - val_mean_absolute_error: 2330.4683 - val_mean_squared_error: 11905459.0000
Epoch 27/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 1345.3384 - mean_absolute_error: 1345.3384 - mean_squared_error: 4800824.5000 - val_loss: 2818.9797 - val_mean_absolute_error: 2818.9797 - val_mean_squared_error: 16771035.0000
Epoch 28/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 1557.6757 - mean_absolute_error: 1557.6757 - mean_squared_error: 6549871.5000 - val_loss: 2713.4380 - val_mean_absolute_error: 2713.4380 - val_mean_squared_error: 16918272.0000
Epoch 29/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 1446.8506 - mean_absolute_error: 1446.8506 - mean_squared_error: 6857143.0000 - val_loss: 2481.3135 - val_mean_absolute_error: 2481.3135 - val_mean_squared_error: 13588558.0000
Epoch 30/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 1571.8591 - mean_absolute_error: 1571.8591 - mean_squared_error: 6174841.0000 - val_loss: 2599.0852 - val_mean_absolute_error: 2599.0852 - val_mean_squared_error: 15833189.0000
Epoch 31/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 1247.4487 - mean_absolute_error: 1247.4487 - mean_squared_error: 5178411.5000 - val_loss: 2769.5166 - val_mean_absolute_error: 2769.5166 - val_mean_squared_error: 18479286.0000
Epoch 32/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 1335.6226 - mean_absolute_error: 1335.6226 - mean_squared_error: 6015630.0000 - val_loss: 2407.6875 - val_mean_absolute_error: 2407.6875 - val_mean_squared_error: 12892582.0000
Epoch 33/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 1359.7081 - mean_absolute_error: 1359.7081 - mean_squared_error: 5383219.5000 - val_loss: 2326.1543 - val_mean_absolute_error: 2326.1543 - val_mean_squared_error: 11575280.0000
Epoch 34/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 1185.8619 - mean_absolute_error: 1185.8619 - mean_squared_error: 4265653.0000 - val_loss: 2622.9185 - val_mean_absolute_error: 2622.9185 - val_mean_squared_error: 14330654.0000
Epoch 35/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 1268.6542 - mean_absolute_error: 1268.6542 - mean_squared_error: 4644430.0000 - val_loss: 2399.2180 - val_mean_absolute_error: 2399.2180 - val_mean_squared_error: 12180400.0000
Epoch 36/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 1275.2749 - mean_absolute_error: 1275.2749 - mean_squared_error: 5190699.0000 - val_loss: 2366.1189 - val_mean_absolute_error: 2366.1189 - val_mean_squared_error: 11821296.0000
Epoch 37/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 1038.3407 - mean_absolute_error: 1038.3407 - mean_squared_error: 3687804.0000 - val_loss: 2632.7290 - val_mean_absolute_error: 2632.7290 - val_mean_squared_error: 15665940.0000
Epoch 38/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 1246.0815 - mean_absolute_error: 1246.0815 - mean_squared_error: 4823411.5000 - val_loss: 2432.0298 - val_mean_absolute_error: 2432.0298 - val_mean_squared_error: 13241788.0000
Epoch 39/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 1193.2029 - mean_absolute_error: 1193.2029 - mean_squared_error: 4211060.5000 - val_loss: 2268.3879 - val_mean_absolute_error: 2268.3879 - val_mean_squared_error: 11128441.0000
Epoch 40/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 1097.3339 - mean_absolute_error: 1097.3339 - mean_squared_error: 3589669.0000 - val_loss: 2379.1648 - val_mean_absolute_error: 2379.1648 - val_mean_squared_error: 12430510.0000
Epoch 41/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 1047.8274 - mean_absolute_error: 1047.8274 - mean_squared_error: 3284905.7500 - val_loss: 2285.1309 - val_mean_absolute_error: 2285.1309 - val_mean_squared_error: 11368319.0000
Epoch 42/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 1011.3698 - mean_absolute_error: 1011.3698 - mean_squared_error: 3602194.2500 - val_loss: 2441.7803 - val_mean_absolute_error: 2441.7803 - val_mean_squared_error: 13191879.0000
Epoch 43/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 996.8523 - mean_absolute_error: 996.8523 - mean_squared_error: 3255694.5000 - val_loss: 2320.7297 - val_mean_absolute_error: 2320.7297 - val_mean_squared_error: 11601250.0000
Epoch 44/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 1123.7231 - mean_absolute_error: 1123.7231 - mean_squared_error: 3499859.5000 - val_loss: 2225.0195 - val_mean_absolute_error: 2225.0195 - val_mean_squared_error: 10594796.0000
Epoch 45/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 782.7967 - mean_absolute_error: 782.7967 - mean_squared_error: 1991300.8750 - val_loss: 2231.1934 - val_mean_absolute_error: 2231.1934 - val_mean_squared_error: 10865799.0000
Epoch 46/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 966.8405 - mean_absolute_error: 966.8405 - mean_squared_error: 3076520.2500 - val_loss: 2112.3567 - val_mean_absolute_error: 2112.3567 - val_mean_squared_error: 9804244.0000
Epoch 47/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 849.2690 - mean_absolute_error: 849.2690 - mean_squared_error: 2047685.5000 - val_loss: 2180.0916 - val_mean_absolute_error: 2180.0916 - val_mean_squared_error: 10542160.0000
Epoch 48/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 806.1581 - mean_absolute_error: 806.1581 - mean_squared_error: 1871150.7500 - val_loss: 2227.5649 - val_mean_absolute_error: 2227.5649 - val_mean_squared_error: 11276229.0000
Epoch 49/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 787.4567 - mean_absolute_error: 787.4567 - mean_squared_error: 1945472.1250 - val_loss: 2318.3408 - val_mean_absolute_error: 2318.3408 - val_mean_squared_error: 12318765.0000
Epoch 50/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 803.2997 - mean_absolute_error: 803.2997 - mean_squared_error: 2005288.6250 - val_loss: 2196.8945 - val_mean_absolute_error: 2196.8945 - val_mean_squared_error: 11146698.0000
Epoch 51/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 747.9939 - mean_absolute_error: 747.9939 - mean_squared_error: 1718385.0000 - val_loss: 2194.5442 - val_mean_absolute_error: 2194.5442 - val_mean_squared_error: 11054466.0000
Epoch 52/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 742.0358 - mean_absolute_error: 742.0358 - mean_squared_error: 1782313.0000 - val_loss: 2187.7129 - val_mean_absolute_error: 2187.7129 - val_mean_squared_error: 10953431.0000
Epoch 53/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 630.4565 - mean_absolute_error: 630.4565 - mean_squared_error: 1266220.8750 - val_loss: 2196.9744 - val_mean_absolute_error: 2196.9744 - val_mean_squared_error: 10973360.0000
Epoch 54/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 638.6019 - mean_absolute_error: 638.6019 - mean_squared_error: 1257389.3750 - val_loss: 2181.7520 - val_mean_absolute_error: 2181.7520 - val_mean_squared_error: 10523829.0000
Epoch 55/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 562.6535 - mean_absolute_error: 562.6535 - mean_squared_error: 1026817.2500 - val_loss: 2192.7173 - val_mean_absolute_error: 2192.7173 - val_mean_squared_error: 10624782.0000
Epoch 56/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 623.1542 - mean_absolute_error: 623.1542 - mean_squared_error: 1054117.1250 - val_loss: 2127.1699 - val_mean_absolute_error: 2127.1699 - val_mean_squared_error: 9622951.0000
Epoch 57/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 694.1593 - mean_absolute_error: 694.1593 - mean_squared_error: 1211546.1250 - val_loss: 2068.2166 - val_mean_absolute_error: 2068.2166 - val_mean_squared_error: 8797718.0000
Epoch 58/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 692.1732 - mean_absolute_error: 692.1732 - mean_squared_error: 1117968.0000 - val_loss: 2154.6914 - val_mean_absolute_error: 2154.6914 - val_mean_squared_error: 9472389.0000
Epoch 59/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 593.0813 - mean_absolute_error: 593.0813 - mean_squared_error: 906159.0000 - val_loss: 2232.2622 - val_mean_absolute_error: 2232.2622 - val_mean_squared_error: 10411735.0000
Epoch 60/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 625.5481 - mean_absolute_error: 625.5481 - mean_squared_error: 949862.4375 - val_loss: 2200.5576 - val_mean_absolute_error: 2200.5576 - val_mean_squared_error: 10077509.0000
Epoch 61/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 553.2557 - mean_absolute_error: 553.2557 - mean_squared_error: 792789.3750 - val_loss: 2127.7617 - val_mean_absolute_error: 2127.7617 - val_mean_squared_error: 9260950.0000
Epoch 62/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 565.1712 - mean_absolute_error: 565.1712 - mean_squared_error: 826730.1875 - val_loss: 2214.1150 - val_mean_absolute_error: 2214.1150 - val_mean_squared_error: 10185660.0000
Epoch 63/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 500.7474 - mean_absolute_error: 500.7474 - mean_squared_error: 667612.0000 - val_loss: 2184.2378 - val_mean_absolute_error: 2184.2378 - val_mean_squared_error: 9861054.0000
Epoch 64/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 658.1285 - mean_absolute_error: 658.1285 - mean_squared_error: 750035.3750 - val_loss: 2218.6299 - val_mean_absolute_error: 2218.6299 - val_mean_squared_error: 10342363.0000
Epoch 65/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 523.6195 - mean_absolute_error: 523.6195 - mean_squared_error: 805494.6875 - val_loss: 2145.3401 - val_mean_absolute_error: 2145.3401 - val_mean_squared_error: 9418899.0000
Epoch 66/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 478.3872 - mean_absolute_error: 478.3872 - mean_squared_error: 565534.0000 - val_loss: 2216.5266 - val_mean_absolute_error: 2216.5266 - val_mean_squared_error: 10433118.0000
Epoch 67/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 527.4887 - mean_absolute_error: 527.4887 - mean_squared_error: 805392.2500 - val_loss: 2176.3123 - val_mean_absolute_error: 2176.3123 - val_mean_squared_error: 10206224.0000
Epoch 68/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 581.9276 - mean_absolute_error: 581.9276 - mean_squared_error: 625235.3750 - val_loss: 2239.7109 - val_mean_absolute_error: 2239.7109 - val_mean_squared_error: 11215206.0000
Epoch 69/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 571.0060 - mean_absolute_error: 571.0060 - mean_squared_error: 771118.3750 - val_loss: 2164.3855 - val_mean_absolute_error: 2164.3855 - val_mean_squared_error: 10094250.0000
Epoch 70/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 538.8622 - mean_absolute_error: 538.8622 - mean_squared_error: 668961.5000 - val_loss: 2141.0227 - val_mean_absolute_error: 2141.0227 - val_mean_squared_error: 9989225.0000

In [11]:
#Model Evalution
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
y_pred=model.predict(X_test)
mae=mean_absolute_error(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)
r2=r2_score(y_test,y_pred)

print(f'Mean Absolute Error: {mae}')
print(f'Mean Squared Error: {mse}')
print(f'R-squared: {r2}')

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
Mean Absolute Error: 1925.966094035823
Mean Squared Error: 9264723.284153717
R-squared: 0.8826418621585431

In [13]:
# Example New Data
new_data=X.iloc[[0]]
new_data_precessed=preprocessor.transform(new_data)

predicted_price=model.predict(new_data_precessed)
print(f'Predicted Price: {predicted_price[0][0]}')

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 391ms/step
Predicted Price: 14224.5810546875